### ISSUE TITLE
Submited photo is not saving.

### ISSUE THREAD

**Issue by Ja-Sny** [Ja-Sny/project_Broccoli#12]

**Comment by Ja-Sny** [comment]
```
Traceback (most recent call last):
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\matim\PycharmProjects\project_Broccoli\appData\routes.py", line 165, in new_post_publish
    carPhoto = save_picture(formData.photo)
  File "C:\Users\matim\PycharmProjects\project_Broccoli\appData\routes.py", line 152, in save_picture
    i = Image.open(form_picture)
  File "C:\Users\matim\AppData\Local\Programs\Python\Python310\Lib\site-packages\PIL\Image.py", line 2953, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '22774e7dbd2a3030e3e0c0b7381dee3e.png'
```

**Comment by Ja-Sny** [comment]
Photo is now uploading to server.
